# PANDAS COMPREHENSIVE METHODS & ATTRIBUTES REFERENCE

In [1]:
import pandas as pd
import numpy as np

In [2]:
## Create sample data
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'Salary': [50000, 60000, 75000, 80000, 55000],
    'Dept': ['HR', 'IT', 'IT', 'Finance', 'HR']
})
df

      Name  Age  Salary     Dept
0    Alice   25   50000       HR
1      Bob   30   60000       IT
2  Charlie   35   75000       IT
3    David   40   80000  Finance
4      Eve   28   55000       HR

#### 1. BASIC ATTRIBUTES (read-only info about the DataFrame)

In [3]:
df.shape              # (rows, columns) tuple

(5, 4)

In [4]:
df.size               # total number of elements

20

In [5]:
df.ndim               # number of dimensions

2

In [6]:
df.dtypes             # data type of each column

Name      object
Age        int64
Salary     int64
Dept      object
dtype: object

In [7]:
df.columns            # column names (Index object)

Index(['Name', 'Age', 'Salary', 'Dept'], dtype='object')

In [8]:
df.index              # row labels (Index object)

RangeIndex(start=0, stop=5, step=1)

In [9]:
df.values             # underlying numpy array

array([['Alice', 25, 50000, 'HR'],
       ['Bob', 30, 60000, 'IT'],
       ['Charlie', 35, 75000, 'IT'],
       ['David', 40, 80000, 'Finance'],
       ['Eve', 28, 55000, 'HR']], dtype=object)

In [10]:
df.T                  # transpose (swap rows/columns)

            0      1        2        3      4
Name    Alice    Bob  Charlie    David    Eve
Age        25     30       35       40     28
Salary  50000  60000    75000    80000  55000
Dept       HR     IT       IT  Finance     HR

In [11]:
df.info()             # memory usage + non-null counts + dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Salary  5 non-null      int64
 3   Dept    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

#### 2. VIEWING / INSPECTING DATA

In [12]:
df.head()             # first 5 rows (default)

      Name  Age  Salary     Dept
0    Alice   25   50000       HR
1      Bob   30   60000       IT
2  Charlie   35   75000       IT
3    David   40   80000  Finance
4      Eve   28   55000       HR

In [13]:
df.head(3)            # first 3 rows

      Name  Age  Salary Dept
0    Alice   25   50000   HR
1      Bob   30   60000   IT
2  Charlie   35   75000   IT

In [14]:
df.tail()             # last 5 rows

      Name  Age  Salary     Dept
0    Alice   25   50000       HR
1      Bob   30   60000       IT
2  Charlie   35   75000       IT
3    David   40   80000  Finance
4      Eve   28   55000       HR

In [15]:
df.tail(2)            # last 2 rows

    Name  Age  Salary     Dept
3  David   40   80000  Finance
4    Eve   28   55000       HR

In [16]:
df.sample(n=2)        # random 2 rows

    Name  Age  Salary     Dept
1    Bob   30   60000       IT
3  David   40   80000  Finance

In [17]:
df.describe()         # summary stats (count, mean, std, min, max, quartiles)

            Age        Salary
count   5.00000      5.000000
mean   31.60000  64000.000000
std     5.94138  12942.179106
min    25.00000  50000.000000
25%    28.00000  55000.000000
50%    30.00000  60000.000000
75%    35.00000  75000.000000
max    40.00000  80000.000000

In [18]:
## Quartiles :
# Understanding spread – Is data tightly grouped or wide?
# Finding outliers – Values beyond 1.5 × IQR are unusual
# Skewness – If Q2 closer to Q1 = right-skewed; closer to Q3 = left-skewed
# Box plots – Box plots visualize all quartiles instantly

In [19]:
df.describe(include='all')  # include object/categorical too

         Name       Age        Salary Dept
count       5   5.00000      5.000000    5
unique      5       NaN           NaN    3
top     Alice       NaN           NaN   HR
freq        1       NaN           NaN    2
mean      NaN  31.60000  64000.000000  NaN
std       NaN   5.94138  12942.179106  NaN
min       NaN  25.00000  50000.000000  NaN
25%       NaN  28.00000  55000.000000  NaN
50%       NaN  30.00000  60000.000000  NaN
75%       NaN  35.00000  75000.000000  NaN
max       NaN  40.00000  80000.000000  NaN

In [20]:
df.memory_usage()     # memory used by each column

Index     132
Name       40
Age        40
Salary     40
Dept       40
dtype: int64

In [21]:
df.isnull()           # boolean DataFrame (True where NaN/None)

    Name    Age  Salary   Dept
0  False  False   False  False
1  False  False   False  False
2  False  False   False  False
3  False  False   False  False
4  False  False   False  False

In [22]:
df.notnull()          # boolean DataFrame (True where NOT null)

   Name   Age  Salary  Dept
0  True  True    True  True
1  True  True    True  True
2  True  True    True  True
3  True  True    True  True
4  True  True    True  True

#### 3. SELECTION / INDEXING

###### By column name(s)

In [23]:
df['Name']            # single column → Series

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [24]:
df[['Name', 'Age']]   # multiple columns → DataFrame

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4      Eve   28

In [25]:
df.Name               # shorthand for df['Name'] (only if no spaces/special chars)

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

###### By row position(s) – iloc (integer location)

In [26]:
df.iloc[0]            # first row

Name      Alice
Age          25
Salary    50000
Dept         HR
Name: 0, dtype: object

In [27]:
df.iloc[0:3]          # rows 0,1,2 (0-indexed, end exclusive)

      Name  Age  Salary Dept
0    Alice   25   50000   HR
1      Bob   30   60000   IT
2  Charlie   35   75000   IT

In [28]:
df.iloc[:, 0]         # all rows, first column

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [29]:
df.iloc[0, 1]         # first row, second column (scalar)

np.int64(25)

###### By row label(s) – loc (label-based)

In [30]:
df.loc[0]             # row with index label 0
                      # Label-based

Name      Alice
Age          25
Salary    50000
Dept         HR
Name: 0, dtype: object

In [31]:
df.loc[0:2]           # rows 0,1,2 (end INCLUSIVE if label-based)

      Name  Age  Salary Dept
0    Alice   25   50000   HR
1      Bob   30   60000   IT
2  Charlie   35   75000   IT

In [32]:
df.loc[:, 'Name']     # all rows, 'Name' column

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [33]:
df.loc[0, 'Name']     # row 0, column 'Name' (scalar)

'Alice'

###### Boolean indexing (filtering)

In [34]:
df[df['Age'] > 28]    # rows where Age > 28

      Name  Age  Salary     Dept
1      Bob   30   60000       IT
2  Charlie   35   75000       IT
3    David   40   80000  Finance

In [35]:
df[(df['Age'] > 25) & (df['Dept'] == 'IT')]  # multiple conditions

      Name  Age  Salary Dept
1      Bob   30   60000   IT
2  Charlie   35   75000   IT

In [36]:
df.loc[df['Salary'] > 60000, ['Name', 'Salary']]  # filter rows, select cols

      Name  Salary
2  Charlie   75000
3    David   80000

#### 4. ADDING / REMOVING / MODIFYING COLUMNS

In [37]:
df['Bonus'] = df['Salary'] * 0.1  # create new column via assignment

In [38]:
df.assign(Bonus=df['Salary']*0.1) # create new column (returns new df, doesn't modify original)

      Name  Age  Salary     Dept   Bonus
0    Alice   25   50000       HR  5000.0
1      Bob   30   60000       IT  6000.0
2  Charlie   35   75000       IT  7500.0
3    David   40   80000  Finance  8000.0
4      Eve   28   55000       HR  5500.0

In [39]:
df.drop('Bonus', axis=1)           # remove a column (axis=1 for columns, axis=0 for rows), doesn't modify original

      Name  Age  Salary     Dept
0    Alice   25   50000       HR
1      Bob   30   60000       IT
2  Charlie   35   75000       IT
3    David   40   80000  Finance
4      Eve   28   55000       HR

In [40]:
df.drop(columns=['Bonus'])         # alternative syntax for dropping columns, doesn't modify the original

      Name  Age  Salary     Dept
0    Alice   25   50000       HR
1      Bob   30   60000       IT
2  Charlie   35   75000       IT
3    David   40   80000  Finance
4      Eve   28   55000       HR

In [41]:
df.pop('Bonus')                    # remove & return a column as Series

0    5000.0
1    6000.0
2    7500.0
3    8000.0
4    5500.0
Name: Bonus, dtype: float64

In [42]:
df.rename(columns={'Age': 'Years'})  # rename columns (returns new df)

      Name  Years  Salary     Dept
0    Alice     25   50000       HR
1      Bob     30   60000       IT
2  Charlie     35   75000       IT
3    David     40   80000  Finance
4      Eve     28   55000       HR

In [43]:
df.rename(columns={'Age': 'Years'}, inplace=True)  # rename in place

#### 5. ADDING / REMOVING ROWS

In [44]:
new_row = pd.DataFrame({'Name': ['Frank'], 'Age': [45], 'Salary': [90000], 'Dept': ['Finance']})

In [45]:
df = pd.concat([df, new_row], ignore_index=True)  # append a row

In [46]:
df.drop(0, axis=0)                 # remove row at index 0

      Name  Years  Salary     Dept   Age
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN
5    Frank    NaN   90000  Finance  45.0

In [47]:
df.drop(0)                         # shorthand (axis=0 is default)

      Name  Years  Salary     Dept   Age
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN
5    Frank    NaN   90000  Finance  45.0

In [48]:
df.drop([0, 2])                    # remove multiple rows

    Name  Years  Salary     Dept   Age
1    Bob   30.0   60000       IT   NaN
3  David   40.0   80000  Finance   NaN
4    Eve   28.0   55000       HR   NaN
5  Frank    NaN   90000  Finance  45.0

In [49]:
df.drop(df[df['Age'] > 35].index)  # remove rows matching condition

      Name  Years  Salary     Dept  Age
0    Alice   25.0   50000       HR  NaN
1      Bob   30.0   60000       IT  NaN
2  Charlie   35.0   75000       IT  NaN
3    David   40.0   80000  Finance  NaN
4      Eve   28.0   55000       HR  NaN

#### 6. DATA CLEANING / HANDLING MISSING VALUES

In [50]:
df.isnull()           # check for NaN/None

    Name  Years  Salary   Dept    Age
0  False  False   False  False   True
1  False  False   False  False   True
2  False  False   False  False   True
3  False  False   False  False   True
4  False  False   False  False   True
5  False   True   False  False  False

In [51]:
df.isna()             # alias for isnull()

    Name  Years  Salary   Dept    Age
0  False  False   False  False   True
1  False  False   False  False   True
2  False  False   False  False   True
3  False  False   False  False   True
4  False  False   False  False   True
5  False   True   False  False  False

In [52]:
df.isnull().sum()     # count NaNs per column

Name      0
Years     1
Salary    0
Dept      0
Age       5
dtype: int64

In [53]:
df.dropna()           # remove rows with any NaN

Empty DataFrame
Columns: [Name, Years, Salary, Dept, Age]
Index: []

In [54]:
df.dropna(axis=1)     # remove columns with any NaN

      Name  Salary     Dept
0    Alice   50000       HR
1      Bob   60000       IT
2  Charlie   75000       IT
3    David   80000  Finance
4      Eve   55000       HR
5    Frank   90000  Finance

In [55]:
df.dropna(subset=['Age'])  # remove rows where 'Age' is NaN

    Name  Years  Salary     Dept   Age
5  Frank    NaN   90000  Finance  45.0

In [56]:
df.fillna(0)          # replace NaN with 0

      Name  Years  Salary     Dept   Age
0    Alice   25.0   50000       HR   0.0
1      Bob   30.0   60000       IT   0.0
2  Charlie   35.0   75000       IT   0.0
3    David   40.0   80000  Finance   0.0
4      Eve   28.0   55000       HR   0.0
5    Frank    0.0   90000  Finance  45.0

In [57]:
df.fillna(df.mean(numeric_only = True))  # replace NaN with column mean

      Name  Years  Salary     Dept   Age
0    Alice   25.0   50000       HR  45.0
1      Bob   30.0   60000       IT  45.0
2  Charlie   35.0   75000       IT  45.0
3    David   40.0   80000  Finance  45.0
4      Eve   28.0   55000       HR  45.0
5    Frank   31.6   90000  Finance  45.0

In [58]:
df.ffill()    # [1, 1, 3, 3, 5]  – carry last value down

      Name  Years  Salary     Dept   Age
0    Alice   25.0   50000       HR   NaN
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN
5    Frank   28.0   90000  Finance  45.0

In [59]:
df.bfill()    # [1, 3, 3, 5, 5]  – carry next value up

      Name  Years  Salary     Dept   Age
0    Alice   25.0   50000       HR  45.0
1      Bob   30.0   60000       IT  45.0
2  Charlie   35.0   75000       IT  45.0
3    David   40.0   80000  Finance  45.0
4      Eve   28.0   55000       HR  45.0
5    Frank    NaN   90000  Finance  45.0

#### 7. SORTING

In [64]:
df.sort_values('Age')                # sort by 'Age' ascending

      Name  Years  Salary     Dept   Age
5    Frank    NaN   90000  Finance  45.0
0    Alice   25.0   50000       HR   NaN
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN

In [65]:
df.sort_values('Age', ascending=False)  # descending

      Name  Years  Salary     Dept   Age
5    Frank    NaN   90000  Finance  45.0
0    Alice   25.0   50000       HR   NaN
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN

In [66]:
df.sort_values(['Dept', 'Age'])      # sort by Dept, then Age

      Name  Years  Salary     Dept   Age
5    Frank    NaN   90000  Finance  45.0
3    David   40.0   80000  Finance   NaN
0    Alice   25.0   50000       HR   NaN
4      Eve   28.0   55000       HR   NaN
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN

In [67]:
df.sort_index()                      # sort by row index

      Name  Years  Salary     Dept   Age
0    Alice   25.0   50000       HR   NaN
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN
5    Frank    NaN   90000  Finance  45.0

#### 8. GROUPING & AGGREGATION

In [68]:
df.groupby('Dept')['Salary'].mean()  # mean salary per department

Dept
Finance    85000.0
HR         52500.0
IT         67500.0
Name: Salary, dtype: float64

In [69]:
df.groupby('Dept').agg({'Salary': 'mean', 'Age': 'max'})  # multiple agg per group

          Salary   Age
Dept
Finance  85000.0  45.0
HR       52500.0   NaN
IT       67500.0   NaN

In [70]:
df.groupby('Dept').size()            # count rows per group

Dept
Finance    2
HR         2
IT         2
dtype: int64

In [71]:
df.groupby('Dept').count()           # count non-null values per group

         Name  Years  Salary  Age
Dept
Finance     2      1       2    1
HR          2      2       2    0
IT          2      2       2    0

In [72]:
df.groupby('Dept')['Salary'].sum()   # total salary per department

Dept
Finance    170000
HR         105000
IT         135000
Name: Salary, dtype: int64

In [73]:
df.groupby('Dept')['Age'].apply(lambda x: x.max() - x.min())  # custom agg per group

Dept
Finance    0.0
HR         NaN
IT         NaN
Name: Age, dtype: float64

#### 9. STATISTICAL METHODS

In [74]:
df['Salary'].mean()           # mean

np.float64(68333.33333333333)

In [75]:
df['Salary'].median()         # median (50th percentile)

np.float64(67500.0)

In [76]:
df['Salary'].std()            # standard deviation

np.float64(15705.625319186329)

In [77]:
df['Salary'].var()            # variance

np.float64(246666666.66666666)

In [78]:
df['Salary'].min()            # minimum

np.int64(50000)

In [79]:
df['Salary'].max()            # maximum

np.int64(90000)

In [80]:
df['Salary'].sum()            # sum

np.int64(410000)

In [81]:
df['Salary'].count()          # count non-null values

np.int64(6)

In [82]:
df['Salary'].quantile(0.25)   # 25th percentile

np.float64(56250.0)

In [90]:
df.corr(numeric_only = True)                     # correlation matrix (numeric cols only)

           Years    Salary  Age
Years   1.000000  0.985117  NaN
Salary  0.985117  1.000000  NaN
Age          NaN       NaN  NaN

In [83]:
# Correlation ranges from -1 to +1:

# Value	Meaning
# +1.0	Perfect positive correlation (both increase together)
# +0.5 to +0.9	Strong positive correlation
# +0.0 to +0.5	Weak positive correlation
# 0.0	No correlation (independent)
# -0.5 to -0.9	Strong negative correlation
# -1.0	Perfect negative correlation (one increases, other decreases)

In [91]:
df['Salary'].skew()           # skewness

np.float64(0.22801263931251298)

In [85]:
# Value	        Name	                  Distribution Shape	       Meaning
# 0	            Symmetric	              Bell curve, centered	       Data is perfectly balanced
# +0.5 to +1	Moderately right-skewed	  Tail on right	               Few high values, most low
# > +1	        Highly right-skewed	      Long tail right	           Very few high outliers
# -0.5 to -1	Moderately left-skewed	  Tail on left	               Few low values, most high
# < -1	        Highly left-skewed	      Long tail left	           Very few low outliers

In [92]:
df['Salary'].kurtosis()       # kurtosis
                              # Kurtosis measures how PEAKED the data is and how FAT the tails are.

np.float64(-1.759952520087654)

In [86]:
# Range	          Category	              Meaning
# -0.5 to +0.5	  Very close to 0	      Nearly normal, almost no skew from standard
# +0.5 to +1.0	  Slightly positive	      Slightly more peaked, few more outliers
# +1.0 to +2.0	  Moderately positive	  Noticeably peaked, more outliers expected
# > +2.0	      High positive	          Very peaked, many outliers
# -0.5 to -1.0	  Slightly negative	      Slightly flatter, fewer outliers
# -1.0 to -2.0	  Moderately negative	  Noticeably flat, very few outliers
# < -2.0	      High negative	          Very flat, almost no outliers

#### 10. MERGING / JOINING / COMBINING

In [88]:
df1 = pd.DataFrame({
    'Key' : [1, 2, 3, 4, 5],
    'Value' : [34, 65, 63, 39, 75]
})
df2 = pd.DataFrame({
    'Key' : [0, 3, 6, 5, 8],
    'Value' : [85, 15, 87, 19, 64]
})

In [89]:
pd.merge(df1, df2, on='Key')          # inner join on 'Key'

   Key  Value_x  Value_y
0    3       63       15
1    5       75       19

In [90]:
pd.merge(df1, df2, on='Key', how='left')   # left join

   Key  Value_x  Value_y
0    1       34      NaN
1    2       65      NaN
2    3       63     15.0
3    4       39      NaN
4    5       75     19.0

In [91]:
pd.merge(df1, df2, on='Key', how='right')  # right join

   Key  Value_x  Value_y
0    0      NaN       85
1    3     63.0       15
2    6      NaN       87
3    5     75.0       19
4    8      NaN       64

In [92]:
pd.merge(df1, df2, on='Key', how='outer')  # outer join

   Key  Value_x  Value_y
0    0      NaN     85.0
1    1     34.0      NaN
2    2     65.0      NaN
3    3     63.0     15.0
4    4     39.0      NaN
5    5     75.0     19.0
6    6      NaN     87.0
7    8      NaN     64.0

In [93]:
pd.concat([df1, df2])                 # stack vertically

   Key  Value
0    1     34
1    2     65
2    3     63
3    4     39
4    5     75
0    0     85
1    3     15
2    6     87
3    5     19
4    8     64

In [94]:
pd.concat([df1, df2], axis=1)         # stack horizontally

   Key  Value  Key  Value
0    1     34    0     85
1    2     65    3     15
2    3     63    6     87
3    4     39    5     19
4    5     75    8     64

#### 11. UNIQUE / DUPLICATES

In [100]:
df['Dept'].unique()                   # unique values in a column (array)

array(['HR', 'IT', 'Finance'], dtype=object)

In [101]:
df['Dept'].nunique()                  # count unique values

3

In [102]:
df.duplicated()                       # boolean Series (True if row is duplicate)

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [103]:
df.duplicated(subset=['Name'])        # check duplicates on specific column(s)

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [104]:
df.drop_duplicates()                  # remove duplicate rows

      Name  Years  Salary     Dept   Age
0    Alice   25.0   50000       HR   NaN
1      Bob   30.0   60000       IT   NaN
2  Charlie   35.0   75000       IT   NaN
3    David   40.0   80000  Finance   NaN
4      Eve   28.0   55000       HR   NaN
5    Frank    NaN   90000  Finance  45.0

In [105]:
df.drop_duplicates(subset=['Dept'])   # remove duplicates based on column(s)

    Name  Years  Salary     Dept  Age
0  Alice   25.0   50000       HR  NaN
1    Bob   30.0   60000       IT  NaN
3  David   40.0   80000  Finance  NaN

#### 12. VALUE COUNTS / FREQUENCY

In [95]:
df['Dept'].value_counts()             # count occurrences (Series, sorted desc)

Dept
HR         2
IT         2
Finance    2
Name: count, dtype: int64

In [96]:
df['Dept'].value_counts(normalize=True)  # as proportions/percentages

Dept
HR         0.333333
IT         0.333333
Finance    0.333333
Name: proportion, dtype: float64

In [97]:
df['Age'].value_counts(bins=5)        # histogram bins

(44.991, 45.009]    1
(44.954, 44.973]    0
(44.973, 44.991]    0
(45.009, 45.027]    0
(45.027, 45.045]    0
Name: count, dtype: int64

#### 13. APPLY / MAP / TRANSFORM

In [98]:
df['Age'].apply(lambda x: x + 1)      # apply function to each element

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5    46.0
Name: Age, dtype: float64

In [99]:
df.apply(lambda row: row['Salary'] * row['Age'], axis=1)  # apply to rows

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5    4050000.0
dtype: float64

In [100]:
df['Dept'].map({'HR': 'Human Resources', 'IT': 'Information Tech'})  # map values

0     Human Resources
1    Information Tech
2    Information Tech
3                 NaN
4     Human Resources
5                 NaN
Name: Dept, dtype: object

In [101]:
df['Age'].transform(lambda x: (x - x.mean()) / x.std())  # transform (same shape)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: Age, dtype: float64

#### 14. STRING METHODS (on Series of strings)

In [113]:
df['Name'].str.lower()                # lowercase

0      alice
1        bob
2    charlie
3      david
4        eve
5      frank
Name: Name, dtype: object

In [114]:
df['Name'].str.upper()                # uppercase

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4        EVE
5      FRANK
Name: Name, dtype: object

In [115]:
df['Name'].str.len()                  # length of each string

0    5
1    3
2    7
3    5
4    3
5    5
Name: Name, dtype: int64

In [116]:
df['Name'].str.startswith('A')        # boolean Series

0     True
1    False
2    False
3    False
4    False
5    False
Name: Name, dtype: bool

In [117]:
df['Name'].str.replace('a', 'X')      # replace substring

0      Alice
1        Bob
2    ChXrlie
3      DXvid
4        Eve
5      FrXnk
Name: Name, dtype: object

In [118]:
df['Name'].str.split(' ')             # split string → list per row

0      [Alice]
1        [Bob]
2    [Charlie]
3      [David]
4        [Eve]
5      [Frank]
Name: Name, dtype: object

In [119]:
df['Name'].str.extract(r'(\w)(\w)')   # regex extract groups

   0  1
0  A  l
1  B  o
2  C  h
3  D  a
4  E  v
5  F  r

#### 15. DATE/TIME OPERATIONS

In [120]:
# Convert to datetime
df['Date'] = pd.to_datetime(['2024-01-01', '2024-02-01', '2024-03-01', 
                              '2024-04-01', '2024-05-01', '2024-06-01'])

In [121]:
df['Date'].dt.year                    # extract year

0    2024
1    2024
2    2024
3    2024
4    2024
5    2024
Name: Date, dtype: int32

In [122]:
df['Date'].dt.month                   # extract month

0    1
1    2
2    3
3    4
4    5
5    6
Name: Date, dtype: int32

In [123]:
df['Date'].dt.day                     # extract day

0    1
1    1
2    1
3    1
4    1
5    1
Name: Date, dtype: int32

In [124]:
df['Date'].dt.dayofweek               # 0=Monday, 6=Sunday

0    0
1    3
2    4
3    0
4    2
5    5
Name: Date, dtype: int32

In [125]:
df['Date'].dt.strftime('%Y-%m')       # format as string

0    2024-01
1    2024-02
2    2024-03
3    2024-04
4    2024-05
5    2024-06
Name: Date, dtype: object

#### 16. RESHAPE / PIVOT / MELT

In [126]:
# Pivot table
pivot_table = df.pivot_table(values='Salary', index='Dept', aggfunc='mean')

In [127]:
# Melt (wide to long)
melted = pd.melt(df, id_vars=['Name'], value_vars=['Age', 'Salary'])

In [128]:
# Pivot (long to wide)
pivot = df.pivot(index='Name', columns='Dept', values='Salary')

#### 17. WRITING / READING FILES

In [129]:
# CSV
df.to_csv('data.csv', index=False)    # write to CSV
df_read = pd.read_csv('data.csv')     # read from CSV

In [ ]:
# Excel
df.to_excel('data.xlsx', sheet_name='Sheet1')
df_read = pd.read_excel('data.xlsx')

In [ ]:
# JSON
df.to_json('data.json')
df_read = pd.read_json('data.json')

#### 18. ITERATION (usually avoid; vectorize instead)

In [136]:
for idx, row in df.iterrows():        # iterate by row (slow)
    print(row['Name'], row['Age'])

Alice nan
Bob nan
Charlie nan
David nan
Eve nan
Frank 45.0

In [139]:
for row in df.itertuples(index=True):      # faster iteration
    print(row.Name, row.Age)
    print(row.Index)  # access index via row.Index

Alice nan
0
Bob nan
1
Charlie nan
2
David nan
3
Eve nan
4
Frank 45.0
5

In [143]:
for col, series in df.items():        # iterate by column
    if series.dtype in ['int64', 'float64']:  # only numeric
        print(col, series.mean())

Years 31.6
Salary 68333.33333333333
Age 45.0

#### 19. FILTERING / QUERYING

In [144]:
df[df['Age'] > 30]                    # boolean mask

    Name  Years  Salary     Dept   Age       Date
5  Frank    NaN   90000  Finance  45.0 2024-06-01

In [145]:
df.query('Age > 30')                  # query syntax (cleaner)

    Name  Years  Salary     Dept   Age       Date
5  Frank    NaN   90000  Finance  45.0 2024-06-01

In [146]:
df.query('Age > 30 and Dept == "IT"') # multiple conditions

Empty DataFrame
Columns: [Name, Years, Salary, Dept, Age, Date]
Index: []

In [147]:
df.loc[df['Age'].between(25, 35)]     # range query

Empty DataFrame
Columns: [Name, Years, Salary, Dept, Age, Date]
Index: []

#### 20. USEFUL UTILITY METHODS

In [ ]:
df.copy()                             # make a shallow copy

In [ ]:
df.copy(deep=True)                    # deep copy

In [ ]:
df.reset_index()                      # reset row index to 0,1,2,…

In [ ]:
df.set_index('Name')                  # set column as row index

In [ ]:
df.astype({'Age': 'int', 'Salary': 'float'})  # change data types

In [ ]:
df.where(df > 50000)                  # keep values > 50000, else NaN

In [ ]:
df.clip(lower=25000, upper=80000)     # clip values to range

In [ ]:
df.nlargest(2, 'Salary')              # 2 rows with largest Salary

In [ ]:
df.nsmallest(2, 'Age')                # 2 rows with smallest Age

In [148]:
df.sample(frac=0.5)                   # random sample (50% of data)

    Name  Years  Salary     Dept   Age       Date
4    Eve   28.0   55000       HR   NaN 2024-05-01
5  Frank    NaN   90000  Finance  45.0 2024-06-01
1    Bob   30.0   60000       IT   NaN 2024-02-01